name: master-thesis-sli0124
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - conda-forge::pytorch
  - anaconda::pandas
  - anaconda::tqdm
  - conda-forge::beautifulsoup4
  - anaconda::requests
  - anaconda::pylint
  - anaconda::matplotlib
  - conda-forge::seaborn
